version: 2
jobs:
  build_and_test:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: 
          name: restore
          command: dotnet restore
      - run: dotnet build
      - run: dotnet test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test